import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,quotaTransaction,LIMITS} from './captcha/service.mjs';
import {parseSandboxTarget} from './captcha/service.mjs';
import {submissionTransaction} from './captcha/audit.mjs';
test('full URL survives normalization',()=>{assert.equal(parseSandboxTarget('tgrn.org/check?a=1#step').url,'https://tgrn.org/check?a=1#step');assert.equal(parseSandboxTarget('2606:4700:4700::1111').url,'https://[2606:4700:4700::1111]/');});
test('stream-first startup skips capture, and two opens reuse one browser',async()=>{const h=harness();const {token,needsOpen,report}=JSON.parse((await h.handler(event({action:'start',target:'tgrn.org/path?x=1',streamFirst:true}))).body);assert.equal(needsOpen,true);assert.equal(report,null);assert.equal(h.calls.captures.length,0);for(let i=0;i<2;i++)assert.equal((await h.handler(event({action:'open',token,target:'https://different.com'}))).statusCode,200);assert.equal((await h.handler(event({action:'open',token}))).statusCode,429);assert.equal(h.calls.starts.length,1);assert.equal(h.calls.captures[0][1],'https://tgrn.org/path?x=1');});
test('recording failure prevents allocation and quota rejection is logged',async()=>{const failed=harness({recordSubmission:async()=>{throw new Error();}});assert.equal((await failed.handler(event({action:'start',target:'example.com'}))).statusCode,503);assert.equal(failed.calls.starts.length,0);const events=[];const h=harness({reserve:async()=>{throw quotaError();},recordSubmission:async()=>events.push('submitted'),auditUpdate:async(_,type)=>events.push(type)});assert.equal((await h.handler(event({action:'start',target:'example.com'}))).statusCode,429);assert.deepEqual(events,['submitted','rate_limited']);});
test('audit stores redacted URL and bounded retention',()=>{const now=1789344000;const q=submissionTransaction({table:'test',key:'sandbox:session:abc',target:'https://example.com/check?token=secret-value#private-fragment',network:'8.8.8.8',now});const row=q.TransactItems.at(-1).Put.Item;assert.equal(row.submittedUrl,'https://example.com');assert.equal(row.queryKeys,undefined);assert.equal(row.expires,now+30*86400);assert.equal(q.TransactItems[0].Update.ExpressionAttributeValues[':max'],1000);assert.doesNotMatch(JSON.stringify(q),/secret-value|private-fragment|8\.8\.8\.8/);});
const event=(body,ip='8.8.8.8')=>({headers:{origin:'https://smitheylab.com','content-type':'application/json'},requestContext:{http:{method:'POST',sourceIp:ip}},body:JSON.stringify(body)});

test('long member session reserves shared seconds and stop never refunds time',async()=>{
 const h=harness();h.rows.set('sandbox:settings',{dailySeconds:300,monthlySeconds:6000,maxSessionSeconds:300,revision:1});
 const member={memberSub:'11111111-1111-1111-1111-111111111111',memberMaxSeconds:300};
 const first=await h.handler({...event({action:'start',target:'example.com',sessionSeconds:240,streamFirst:true}),...member});
 assert.equal(first.statusCode,200);assert.equal(h.calls.starts[0].sessionTimeoutSeconds,240);
 await h.handler({...event({action:'stop',token:JSON.parse(first.body).token}),...member});h.advance(301);
 assert.equal((await h.handler({...event({action:'start',target:'example.com',sessionSeconds:120}),...member})).statusCode,429);
 assert.equal(h.calls.starts.length,1);
 assert.equal((await h.handler(event({action:'start',target:'example.com'},'1.1.1.1'))).statusCode,200);
 assert.equal([...h.rows.entries()].find(([key])=>key.startsWith('sandbox:seconds:day:'))[1].count,300);
});
test('member audit identity comes only from verified top-level identity',async()=>{const records=[];const h=harness({recordSubmission:async input=>records.push(input)});await h.handler(event({action:'start',target:'example.com',memberSub:'11111111-1111-1111-1111-111111111111'}));assert.equal(records[0].memberSub,undefined);h.advance(121);await h.handler({...event({action:'start',target:'example.com'}),memberSub:'22222222-2222-2222-2222-222222222222'});assert.equal(records[1].memberSub,'22222222-2222-2222-2222-222222222222');});
test('exact quota response and durable event agree without another allocation',async()=>{const events=[];const error=Object.assign(new Error(),{name:'TransactionCanceledException',CancellationReasons:[{Code:'None'},{Code:'None'},{Code:'ConditionalCheckFailed'},{Code:'None'},{Code:'None'}]});const h=harness({reserve:async()=>{throw error;},auditUpdate:async(key,type,details)=>events.push({type,...details})});const response=await h.handler(event({action:'start',target:'example.com'}));const body=JSON.parse(response.body);assert.equal(response.statusCode,429);assert.equal(body.code,'NETWORK_DAILY_LIMIT');assert.deepEqual(events[0].codes,['NETWORK_DAILY_LIMIT']);assert.equal(events[0].retryAt,body.retryAt);assert.ok(Number(response.headers['retry-after'])>120);assert.equal(h.calls.starts.length,0);});
const quotaError=()=>Object.assign(new Error(),{name:'TransactionCanceledException',CancellationReasons:[{Code:'ConditionalCheckFailed'}]});
function harness(overrides={}){
  const rows=new Map(),calls={starts:[],stops:[],captures:[]};let now=Date.UTC(2026,8,1)/1000;
  // Synchronous commit models DynamoDB's all-or-nothing transaction admission.
  const reserve=async args=>{const transaction=quotaTransaction(args),updates=[];for(const item of transaction.TransactItems){if(item.ConditionCheck){const old=rows.get(item.ConditionCheck.Key.id);if(old&&old.revision!==args.budget.revision)throw quotaError();continue;}if(item.Update){const u=item.Update,v=u.ExpressionAttributeValues,old=rows.get(u.Key.id)||{};if(':seconds' in v){if((old.count||0)>v[':remaining'])throw quotaError();updates.push([u.Key.id,{count:(old.count||0)+v[':seconds']}]);}else if(':limit' in v){if((old.count||0)>=v[':limit'])throw quotaError();updates.push([u.Key.id,{count:(old.count||0)+1}]);}else{if(old.untilTime>now)throw quotaError();updates.push([u.Key.id,{untilTime:v[':until']}]);}}else{updates.push([item.Put.Item.id,item.Put.Item]);}}for(const [id,value] of updates)rows.set(id,value);};
  const deps={recordSubmission:async()=>{},auditUpdate:async()=>{},env:{ALLOWED_ORIGINS:'https://smitheylab.com',RATE_TABLE:'test',BROWSER_ID:'test_browser',SANDBOX_ENABLED:'true'},now:()=>now,reserve,resolve:async()=>({}),startBrowser:async input=>{calls.starts.push(input);return{sessionId:'session1'};},stop:async id=>{calls.stops.push(id);},save:async(key,fields)=>rows.set(key,{...rows.get(key),...fields}),read:async key=>rows.get(key),capture:async(...args)=>{calls.captures.push(args);return {verdict:'Fixture evidence only',findings:[]};},browserClient:()=>({attachSession(){},generateLiveViewUrl:async()=>'https://bedrock-agentcore.us-east-1.amazonaws.com/test'})};
  deps.reserveOpen=async key=>{const row=rows.get(key);if((row.opens||0)>=2||row.operationUntil>now)throw new Error();row.opens=(row.opens||0)+1;row.operationUntil=now+28;};
  deps.reserveCapture=async key=>{const row=rows.get(key);if(row.captures>=3||row.nextCapture>now)throw new Error();row.captures++;row.nextCapture=now+20;};
  return {handler:createHandler({handover:async()=>{},...deps,...overrides}),calls,rows,advance:seconds=>{now+=seconds;}};
}
test('global lease admits only one simultaneous start across different networks',async()=>{const h=harness();const results=await Promise.all(Array.from({length:20},(_,i)=>h.handler(event({action:'start',target:'example.com'},`8.8.${i}.1`))));assert.equal(results.filter(r=>r.statusCode===200).length,1);assert.equal(h.calls.starts.length,1);assert.equal(results.filter(r=>r.statusCode===429).length,19);});
test('five starts are shared across networks and stop does not refund quotas',async()=>{const h=harness();for(let i=0;i<5;i++){const response=await h.handler(event({action:'start',target:'example.com'},`8.8.${i}.1`));assert.equal(response.statusCode,200);const {token}=JSON.parse(response.body);assert.equal((await h.handler(event({action:'stop',token},`8.8.${i}.1`))).statusCode,200);h.advance(181);}assert.equal((await h.handler(event({action:'start',target:'example.com'},'1.1.1.1'))).statusCode,429);assert.equal(h.calls.starts.length,5);});
test('one network gets two starts per day',async()=>{const h=harness();await h.handler(event({action:'start',target:'example.com'}));h.advance(121);assert.equal((await h.handler(event({action:'start',target:'example.com'}))).statusCode,200);h.advance(121);assert.equal((await h.handler(event({action:'start',target:'example.com'}))).statusCode,429);assert.equal(h.calls.starts.length,2);});
test('calendar monthly backstop stops day-to-day usage at100',async()=>{const h=harness();for(let d=0;d<21;d++){for(let i=0;i<5;i++){const response=await h.handler(event({action:'start',target:'example.com'},`8.8.${i}.1`));assert.equal(response.statusCode,d<20?200:429);h.advance(181);}h.advance(86400-905);}assert.equal(h.calls.starts.length,100);});
test('limiter failure and kill switch fail closed before browser allocation',async()=>{for(const overrides of [{reserve:async()=>{throw new Error('offline');}},{env:{ALLOWED_ORIGINS:'https://smitheylab.com',SANDBOX_ENABLED:'false'}}]){const h=harness(overrides);assert.equal((await h.handler(event({action:'start',target:'example.com'}))).statusCode,503);assert.equal(h.calls.starts.length,0);}});
test('private target is rejected before reservation and DNS rejects before paid work',async()=>{const h=harness();assert.equal((await h.handler(event({action:'start',target:'127.0.0.1'}))).statusCode,400);assert.equal(h.rows.size,0);const failing=harness({resolve:async()=>{throw new Error('private answer');}});assert.equal((await failing.handler(event({action:'start',target:'example.com'}))).statusCode,503);assert.equal(failing.calls.starts.length,0);});
test('capture failure produces an inconclusive report and preserves the bounded session',async()=>{const h=harness({capture:async()=>{throw new Error('capture failed');}});const response=await h.handler(event({action:'start',target:'example.com'}));assert.equal(response.statusCode,200);assert.equal(JSON.parse(response.body).report.level,'inconclusive');assert.equal(h.calls.starts[0].sessionTimeoutSeconds,60);assert.ok([...h.rows.values()].some(row=>row.failureStage==='capture'));});
test('provider timeout and idempotency are fixed by backend, no automation capability returned',async()=>{const h=harness();const response=await h.handler(event({action:'start',target:'example.com',sessionTimeoutSeconds:86400}));assert.equal(response.statusCode,200);assert.equal(h.calls.starts[0].sessionTimeoutSeconds,60);assert.match(h.calls.starts[0].clientToken,/^[a-f0-9]{64}$/);assert.doesNotMatch(response.body,/session1|automation|credentials/i);assert.equal(JSON.parse(response.body).limits.daily,5);});
test('session token cannot be used from another network; capture expires',async()=>{const h=harness();const {token}=JSON.parse((await h.handler(event({action:'start',target:'example.com'}))).body);assert.equal((await h.handler(event({action:'capture',token},'1.1.1.1'))).statusCode,403);h.advance(61);assert.equal((await h.handler(event({action:'capture',token}))).statusCode,410);assert.equal(h.calls.captures.length,1);});
test('only three extra captures and20second cooldown, with stop still available',async()=>{const h=harness();const {token}=JSON.parse((await h.handler(event({action:'start',target:'example.com'}))).body);for(let i=0;i<3;i++){assert.equal((await h.handler(event({action:'capture',token}))).statusCode,200);assert.equal((await h.handler(event({action:'capture',token}))).statusCode,429);if(i<2)h.advance(20);}assert.equal((await h.handler(event({action:'capture',token}))).statusCode,429);assert.equal((await h.handler(event({action:'stop',token}))).statusCode,200);assert.equal(h.calls.captures.length,4);});
test('admission uses one DynamoDB transaction with conditional counters and lease',()=>{const q=quotaTransaction({table:'test',network:'8.8.8.8',now:1789344000,key:'sandbox:session:test'});assert.equal(q.TransactItems.length,8);assert.deepEqual(q.TransactItems.slice(0,3).map(x=>x.Update.ExpressionAttributeValues[':limit']),[5,100,2]);assert.ok(q.TransactItems.every(x=>(x.Update||x.Put||x.ConditionCheck).ConditionExpression));assert.ok(LIMITS.leaseSeconds>LIMITS.seconds+28);});
test('member sessions are owned by identity, not the shared network or a token alone',async()=>{const h=harness(),a='11111111-1111-1111-1111-111111111111',b='22222222-2222-2222-2222-222222222222';const start=await h.handler({...event({action:'start',target:'example.com'}),memberSub:a});const {token}=JSON.parse(start.body);assert.equal(start.statusCode,200);assert.equal((await h.handler({...event({action:'capture',token}),memberSub:b})).statusCode,403);assert.equal((await h.handler(event({action:'capture',token,memberSub:a}))).statusCode,403);assert.equal((await h.handler({...event({action:'stop',token},'1.1.1.1'),memberSub:a})).statusCode,200);});
test('member starts bypass only network quota and still share global budgets and lease',async()=>{const h=harness(),sub='11111111-1111-1111-1111-111111111111';for(let i=0;i<5;i++){assert.equal((await h.handler({...event({action:'start',target:'example.com'}),memberSub:sub})).statusCode,200);h.advance(121);}assert.equal((await h.handler({...event({action:'start',target:'example.com'}),memberSub:sub})).statusCode,429);assert.equal(h.calls.starts.length,5);});
test('public callers cannot opt out of network quota using body fields',async()=>{const h=harness();for(let i=0;i<3;i++){const r=await h.handler(event({action:'start',target:'example.com',memberSub:'11111111-1111-1111-1111-111111111111',member:true}));assert.equal(r.statusCode,i<2?200:429);h.advance(121);}});

test('failed startup handover stops the browser and returns no viewer credentials',async()=>{const h=harness({handover:async()=>{throw Error('handover failed');}});const r=await h.handler(event({action:'start',target:'example.com',streamFirst:true}));assert.equal(r.statusCode,503);assert.deepEqual(h.calls.stops,['session1']);assert.equal(JSON.parse(r.body).liveUrl,undefined);});
test('session rows never contain the raw URL or token, and stop clears ciphertext',async()=>{const h=harness();const r=await h.handler(event({action:'start',target:'https://example.com/private-path?secret-query=value#fragment',streamFirst:true}));assert.equal(r.statusCode,200);const {token}=JSON.parse(r.body),row=[...h.rows.values()].find(x=>x.state==='active');assert.ok(row.targetCipher);assert.equal(row.target,undefined);assert.ok(!JSON.stringify([...h.rows.values()]).includes(token));assert.doesNotMatch(JSON.stringify(row),/private-path|secret-query|fragment/);await h.handler(event({action:'stop',token}));const closed=[...h.rows.values()].find(x=>x.state==='stopped');assert.equal(closed.targetCipher,null);assert.equal(closed.target,null);});
test('terminal startup failure clears encrypted target and stores only classified diagnostics',async()=>{const h=harness({handover:async()=>{throw Error('non-URL-secret-credential');}});await h.handler(event({action:'start',target:'https://example.com/private-path',streamFirst:true}));const row=[...h.rows.values()].find(x=>x.state==='failed');assert.equal(row.targetCipher,null);assert.equal(row.target,null);assert.doesNotMatch(JSON.stringify(row),/non-URL-secret-credential|private-path/);});
