import {installViewerProtection,hostChange,readableReport} from './captcha-protection.js';
const $=id=>document.getElementById(id);
let endpoint='',token='',endsAt=0,captures=0,report=null,connection=null,clock=null,busy=false,opening=false,liveUrl='',generation=0,nextCapture=0,viewOnly=false;
const status=(text,error=false)=>{$('sandbox-status').textContent=text;$('sandbox-status').dataset.state=error?'error':'ready';};
const element=(tag,text)=>{const item=document.createElement(tag);item.textContent=text;return item;};
function controls(){const active=!!token&&Date.now()<endsAt*1000;$('sandbox-start').disabled=busy||active||!endpoint;$('sandbox-capture').disabled=busy||opening||!active||captures>=3||Date.now()<nextCapture;$('sandbox-stop').disabled=!active;$('sandbox-open').disabled=busy||opening||!active;$('sandbox-reconnect').disabled=!active;}
function fit(){const frame=$('sandbox-viewport'),display=$('sandbox-display');const scale=Math.min(frame.clientWidth/1280,Math.max(180,window.innerHeight-210)/800,1);frame.style.height=`${800*scale}px`;display.style.transform=`scale(${scale})`;display.style.left=`${Math.max(0,(frame.clientWidth-1280*scale)/2)}px`;}
new ResizeObserver(fit).observe($('sandbox-viewport'));window.addEventListener('resize',fit);
installViewerProtection({root:$('sandbox-viewport'),notice:text=>{$('sandbox-protection-status').textContent=text;},isViewOnly:()=>viewOnly});
$('sandbox-view-only').addEventListener('change',event=>{viewOnly=event.target.checked;$('sandbox-input-shield').hidden=!viewOnly;$('sandbox-protection-status').textContent=viewOnly?'View-only mode. The remote page and session timer continue running.':'Interactive mode. Clipboard sharing and file transfer remain disabled.';});
async function request(body){const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(31000),cache:'no-store'});let data;try{data=await response.json();}catch{throw new Error('The service could not respond. Any started browser still expires automatically.');}if(!response.ok)throw new Error(data.message||'The service is temporarily unavailable.');return data;}
function render(value){report=value;const change=hostChange(value.requestedUrl,value.url);$('sandbox-host-change').hidden=!change;$('sandbox-host-change').textContent=change?`Different host at capture: ${change.from} to ${change.to}. This can be a redirect or navigation; it does not establish whether the page is safe.`:'';$('sandbox-results').hidden=false;$('sandbox-verdict').textContent=value.verdict;$('sandbox-verdict').dataset.level=value.level;$('sandbox-report-meta').textContent=`Requested: ${value.requestedUrl||''} | Viewed: ${value.url||''} | HTTP ${value.httpStatus??'unknown'} | ${value.title||'Untitled page'}`;const list=$('sandbox-findings');list.replaceChildren();for(const finding of value.findings||[]){const card=element('article','');card.className='checker-result-card';card.append(element('h3',finding.title),element('p',finding.description),element('p',`Evidence source: ${finding.source}`),element('blockquote',finding.evidence));list.append(card);}if(!list.children.length)list.append(element('p','No matching indicators in the captured evidence. This does not establish safety.'));const notes=$('sandbox-limitations');notes.replaceChildren(element('h3','Coverage and limitations'));notes.append(element('p',`Provider indicators: ${(value.providerIndicators||[]).join(', ')||'None observed'}. Frames on page: ${value.frameCount??'unknown'}.`));if(value.navigationNote)notes.append(element('p',value.navigationNote));if(value.coverage?.textTruncated||value.coverage?.inlineScriptsTruncated)notes.append(element('p','Evidence reached a capture size limit; some content was omitted.'));const ul=element('ul','');for(const line of value.limitations||[])ul.append(element('li',line));notes.append(ul);$('sandbox-screenshot-wrap').hidden=!value.screenshot;if(value.screenshot)$('sandbox-screenshot').src=`data:image/jpeg;base64,${value.screenshot}`;else $('sandbox-screenshot').removeAttribute('src');}
function disconnect(){generation++;connection?.disconnect();connection=null;clearInterval(clock);$('sandbox-display').replaceChildren();controls();}
function countdown(){const remaining=Math.max(0,Math.ceil(endsAt-Date.now()/1000));$('sandbox-timer').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')} remaining · no extensions`;controls();if(!remaining){token='';busy=false;opening=false;disconnect();$('sandbox-view-status').textContent='Session expired. Your last captured report remains below.';}}
async function connect(url){
  const attempt=++generation;connection?.disconnect();connection=null;$('sandbox-display').replaceChildren();$('sandbox-view-status').textContent='Connecting live controls...';
  const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.hostname!=='bedrock-agentcore.us-east-1.amazonaws.com')throw new Error('Unexpected viewer endpoint.');
  const dcv=window.dcv;if(!dcv)throw new Error('Viewer could not load.');
  const diagnostics=[];
  dcv.setLogHandler(({domain,message})=>{
    if(!/channel|input/i.test(String(domain))||!/created channel|unable to create|not enabled|not available|status update|failed|rejected|not found/i.test(String(message)))return;
    const safe=String(message).replace(/(?:https?|wss?):\/\/\S+/g,'[endpoint]').replace(/[A-Za-z0-9_=-]{40,}/g,'[redacted]').slice(0,200);
    diagnostics.push(safe);if(diagnostics.length>8)diagnostics.shift();
    $('sandbox-display').dataset.diagnostics=diagnostics.join(' | ');
    console.info('Viewer diagnostic:',safe);
  });
  const extra=()=>parsed.searchParams;
  const auth=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Viewer connection timed out.')),10000);dcv.authenticate(url,{httpExtraSearchParams:extra,promptCredentials:()=>{clearTimeout(timeout);reject(new Error('Viewer authorization failed.'));},error:()=>{clearTimeout(timeout);reject(new Error('Viewer connection failed.'));},success:(_,sessions)=>{clearTimeout(timeout);resolve(sessions[0]);}});});if(attempt!==generation||!token||Date.now()>=endsAt*1000)return;
  const conn=await dcv.connect({url,sessionId:auth.sessionId,authToken:auth.authToken,divId:'sandbox-display',baseUrl:'/assets/dcv/',enabledChannels:['display','input'],clipboardAutoSync:false,volumeLevel:0,observers:{httpExtraSearchParams:extra,disconnect:()=>{if(attempt!==generation)return;$('sandbox-view-status').textContent='Remote view disconnected. The automatic session timeout still applies.';}}});
  if(!conn?.disconnect)throw new Error('Viewer connection failed.');
  if(attempt!==generation||!token||Date.now()>=endsAt*1000){conn.disconnect();return;}
  connection=conn;conn.captureClipboardEvents(false);
  await conn.requestDisplayLayout([{name:'Main Display',rect:{x:0,y:0,width:1280,height:800},primary:true}]).catch(()=>{});
  fit();
  const inputFeatures=await Promise.all(['mouse','keyboard'].map(async name=>{try{return `${name}: ${(await conn.queryFeature(name)).enabled?'available':'unavailable'}`;}catch{return `${name}: unconfirmed`;}}));
  if(attempt===generation)$('sandbox-view-status').textContent=`Live view connected — ${inputFeatures.join('; ')}. Click inside the remote page to focus it.`;
}
async function openSubmitted(){if(!token||opening)return;const current=token;opening=true;controls();status('Opening your submitted URL and checking the page...');try{const data=await request({action:'open',token:current});if(current!==token)return;render(data.report);status(data.report.navigationNote||'Page opened. Interact in the live view, then capture a report.',data.report.pageLoaded===false||data.report.httpStatus>=400);}catch(error){if(current===token)status(error.message,true);}finally{if(current===token){opening=false;controls();}}}
$('sandbox-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||token)return;busy=true;controls();status('Starting your one-minute browser...');try{const data=await request({action:'start',target:$('sandbox-target').value.trim(),streamFirst:true});token=data.token;liveUrl=data.liveUrl;endsAt=Date.now()/1000+Math.min(60,Math.max(0,data.remainingSeconds||0));captures=0;nextCapture=0;opening=false;$('sandbox-capture').textContent='Capture report (3 left)';$('sandbox-results').hidden=true;$('sandbox-session').hidden=false;fit();$('sandbox-session').scrollIntoView({block:'start',behavior:'instant'});countdown();clock=setInterval(countdown,1000);busy=false;controls();const current=token;connect(liveUrl).catch(error=>{if(current===token)$('sandbox-view-status').textContent=`${error.message} Use Reconnect view to retry within this session.`;});if(data.needsOpen)await openSubmitted();else if(data.report)render(data.report);}catch(error){status(error.message,true);}finally{busy=false;controls();}});
$('sandbox-open').addEventListener('click',openSubmitted);
$('sandbox-reconnect').addEventListener('click',()=>{const current=token;connect(liveUrl).catch(error=>{if(current===token)$('sandbox-view-status').textContent=error.message;});});
$('sandbox-fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('sandbox-session').requestFullscreen();fit();}catch{status('Full screen is unavailable in this browser.',true);}});
$('sandbox-capture').addEventListener('click',async()=>{const current=token;busy=true;nextCapture=Date.now()+20000;controls();status('Capturing visible evidence...');try{const data=await request({action:'capture',token:current});if(current!==token)return;captures++;render(data.report);$('sandbox-capture').textContent=`Capture report (${3-captures} left)`;status('Report updated. Allow 20 seconds before the next capture.');}catch(error){if(current===token)status(error.message,true);}finally{if(current===token){busy=false;controls();}}});
$('sandbox-stop').addEventListener('click',async()=>{const current=token;token='';opening=false;busy=true;disconnect();$('sandbox-view-status').textContent='Remote view disconnected.';$('sandbox-timer').textContent='Ending session...';try{const data=await request({action:'stop',token:current});status(data.message);$('sandbox-timer').textContent='Session stopped';}catch(error){status(error.message,true);$('sandbox-timer').textContent='Disconnected; automatic expiry still applies';}finally{busy=false;controls();}});
$('sandbox-export-text').addEventListener('click',()=>{if(!report)return;const url=URL.createObjectURL(new Blob([readableReport(report)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='smithey-lab-inspection.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('sandbox-export').addEventListener('click',()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='smithey-lab-captcha-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('pagehide',()=>{connection?.disconnect();if(token&&endpoint)fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'stop',token}),keepalive:true}).catch(()=>{});});
controls();
try{const response=await fetch('/captcha-config.json',{cache:'no-store'});const config=await response.json();if(config.enabled&&config.endpoint){const url=new URL(config.endpoint);if(url.protocol!=='https:'||!url.hostname.endsWith('.execute-api.us-east-1.amazonaws.com'))throw new Error();endpoint=url.href;status('Ready. Session setup uses part of the one-minute allowance.');}else status('The sandbox is being prepared and is not accepting sessions yet.');}catch{status('Availability could not be checked. Please reload later.',true);}controls();
